language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23

    - extra-android-m2repository
    - extra-google-m2repository

before_install:
 - chmod +x gradlew

script:
   - ./gradlew build connectedCheck